version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=docker_db_demo
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    
  backend:
    build:
      context: ../../backend_nodejs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000